import std.stdio;
import std.format;
import std.algorithm.searching;
import std.algorithm.iteration;
import std.file;
import std.array;
import std.range;
import std.string;
import std.path;

import statemachine;
import types;

void main(string[] args)
{
    if (args.length < 2)
    {
        writeln("Wrong param count!");
        return;
    }

    if (args.length==2)
        args~=args[1].stripExtension~".d";

    string fname = args[1];
    if (!exists(fname))
    {
        writefln("File %s doesn't exists!", fname);
        return;
    }

    string data = readText(fname);

    auto m = new StateMachine(data);

    string generated_code = `//This code was generated by FLTKParser (https://github.com/dvaldespino94/FluidParser)
import fltk_d;
import core.stdc.stdint;

`;
    foreach (node; m.Nodes)
    {
        generated_code ~= node.generate;
    }

    std.file.write(args[2], generated_code);
}
